# Generated by Django 4.1 on 2023-11-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='**********', max_length=100),
        ),
    ]
