# Generated by Django 4.1 on 2023-11-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab_management', '0003_driver_overall_rating_ride_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='vehicle_preference',
        ),
    ]
