# Generated by Django 4.1 on 2023-11-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_management', '0004_remove_ride_vehicle_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
