# Generated by Django 4.1 on 2023-11-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_management', '0005_ride_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='total_feedbacks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
